spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: agripro
    password: agripro
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false
    generate-ddl: false
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: realtime-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.add.type.headers: true
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          newMessageEvent:com.hashjosh.kafkacommon.communication.NewMessageEvent,
          agricultureRegistrationContract:com.hashjosh.kafkacommon.agriculture.AgricultureRegistrationContract,
          farmerRegistrationContract:com.hashjosh.kafkacommon.farmer.FarmerRegistrationContract,
          pcicRegistrationContract:com.hashjosh.kafkacommon.pcic.PcicRegistrationContract,
          applicationSubmittedEvent:com.hashjosh.kafkacommon.application.ApplicationSubmittedEvent,
          verificationEvent:com.hashjosh.kafkacommon.application.VerificationEvent,
          inspectionScheduledEvent:com.hashjosh.kafkacommon.application.InspectionScheduledEvent,
          inspectionCompletedEvent:com.hashjosh.kafkacommon.application.InspectionCompletedEvent,
          policyIssuedEvent:com.hashjosh.kafkacommon.application.PolicyIssuedEvent,
          claimProcessedEvent:com.hashjosh.kafkacommon.application.ClaimProcessedEvent,
          newInvitationEvent:com.hashjosh.kafkacommon.agriculture.NewInvitationEvent

  mail:
    host: smtp.gmail.com
    port: 587
    username: pracullosjohnpaul@gmail.com
    password: vggv yxhs abhp ynrm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML
  encoding: UTF-8

notification:
  from: pracullosjohnpaul@gmail.com
  sender-name: AgriPro Notifications

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

token:
  secret: lJ43fZtwCfh2qNM0uFx3mHSYGh/qrfXUtrM4Vl/kiZE=
  access-token-expiration-ms: 14400000
  access-token-expiration-remember-me-ms: 2592000000
  refresh-token-expiration-ms: 86400000
  refresh-token-expiration-remember-me-ms: 345600000

trusted:
  internal-service-ids:
    - agriculture-service
    - notification-service
    - realtime-service
    - farmer-service
    - pcic-service
    - application-service
    - document-service
    - rsbsa-service
    - program-service

server:
  port: 9998