package com.hashjosh.constant.pcic.enums;

public enum InsuranceStatus {
    PENDING, APPROVED,SCHEDULE_ASSIGNED_FOR_INSPECTION,INSPECTION_COMPLETED,VERIFIED, CLAIMED_ISSUED, POLICY_ISSUED, REJECTED
}
